"""Compile receipt metadata into explicit Godot preloads. Never modifies PNGs."""
from pathlib import Path
import json
ROOT = Path(__file__).resolve().parents[1]
rows = ['extends RefCounted', '# Generated by tools/compile_delivered_art.py from unmodified delivery manifests.', 'const CLIPS = {']
for folder in ['kidnapper_basic_v1', 'kidnapper_reactions_v1', 'effects_v1']:
    data = json.loads((ROOT/'art_delivery'/folder/'manifest.json').read_text(encoding='utf-8-sig'))
    for name, clip in data['animations'].items():
        prefix = 'fx/' if folder == 'effects_v1' else 'enemy/'
        frames = []
        for frame in clip['frames']:
            path = lambda p: 'preload("res://art_delivery/' + folder + '/' + p + '")'
            if isinstance(frame, dict):
                frames.append('{"rear":'+path(frame['rear'])+',"front":'+path(frame['front'])+',"shoulder":Vector2'+str(tuple(frame['shoulder_px']))+'}')
            else:
                frames.append(path(frame))
        asset = next(a for a in data['assets'] if a['file'] == (clip['frames'][0] if isinstance(clip['frames'][0], str) else clip['frames'][0]['rear']))
        anchor = asset.get('anchor_px', asset.get('foot_anchor_px', [16,44]))
        times = [t/1000 if t else 1.0 for t in clip['frame_duration_ms']]
        rows.append('\t"'+prefix+name+'":{"frames":['+','.join(frames)+'],"times":'+str(times)+',"loop":'+str(clip['loop']).lower()+',"anchor":Vector2'+str(tuple(anchor))+'},')
# Approved full motion sets; retain per-direction body and weapon anchors.
for folder in sorted((ROOT/'art_delivery').glob('*_motion_v1')):
    data = json.loads((folder/'manifest.json').read_text(encoding='utf-8-sig'))
    if data.get('character_id') not in ['destroyer','martial_artist','salaryman','ninja','animal_tamer','runner','doberman','bullfrog','hedgehog']: continue
    assets = {a['file']:a for a in data['assets']}
    for name, clip in data['actions'].items():
        paths=clip['frames']; first=assets[paths[0]]
        anchor=first['foot_anchor_px']
        load=lambda f: 'preload("res://art_delivery/'+folder.name+'/'+f+'")'
        frames=[]
        for i,f in enumerate(paths):
            if clip.get('weapon_frames'):
                weapon=clip['weapon_frames'][i]; wa=assets[weapon]['foot_anchor_px']
                frames.append('{"body":'+load(f)+',"weapon":'+load(weapon)+',"weapon_anchor":Vector2'+str(tuple(wa))+'}')
            else: frames.append(load(f))
        times=[v/1000 if v else 1.0 for v in clip['frame_duration_ms']]
        sockets=',"mouth":['+','.join('Vector2'+str(tuple(p)) for p in clip['mouth_socket_px'])+']' if clip.get('mouth_socket_px') else ''
        rows.append('\t"'+data['character_id']+'/'+name+'":{"frames":['+','.join(frames)+'],"times":'+str(times)+',"loop":'+str(clip['loop']).lower()+',"anchor":Vector2'+str(tuple(anchor))+sockets+'},')
rows += ['}', 'const FROG_PARTS = {']
frog=json.loads((ROOT/'art_delivery/bullfrog_motion_v1/manifest.json').read_text(encoding='utf-8'))
for name, part in frog['parts'].items():
    rows.append('\t"'+name+'":{"texture":preload("res://art_delivery/bullfrog_motion_v1/'+part['file']+'"),"anchor":Vector2'+str(tuple(part['anchor_px']))+'},')
rows += ['}', 'const RESOURCES = {']
for kind in ['wood','soil','stone','gold']:
    rows.append('\t"'+kind+'":{'+','.join(str(n)+':preload("res://art_delivery/resource_icons_v1/'+folder+'/'+kind+'.png")' for n,folder in [(24,'hud24'),(48,'ui48'),(96,'ui96')])+'},')
rows += ['}', '''
static func duration(key: String) -> float:
	var total=0.0
	for seconds in CLIPS[key].times: total+=seconds
	return total

static func frame_index(key: String, elapsed: float, hide_finished: bool=false) -> int:
	var clip=CLIPS[key]
	var total=duration(key)
	if hide_finished and elapsed>=total and not clip.loop:return -1
	var time=fmod(maxf(elapsed,0),total) if clip.loop else maxf(elapsed,0)
	for i in range(clip.times.size()):
		if time<clip.times[i]:return i
		time-=clip.times[i]
	return clip.frames.size()-1

static func draw_clip(c: CanvasItem, key: String, origin: Vector2, elapsed: float):
	var index=frame_index(key,elapsed,key.begins_with("fx/"))
	if index<0:return
	c.texture_filter=CanvasItem.TEXTURE_FILTER_NEAREST
	var frame=CLIPS[key].frames[index]
	if frame is Dictionary:
		c.draw_texture(frame.body,(origin-CLIPS[key].anchor).round())
		c.draw_texture(frame.weapon,(origin-frame.weapon_anchor).round())
	else:c.draw_texture(frame,(origin-CLIPS[key].anchor).round())

static func resource(c: CanvasItem, kind: String, center: Vector2, size: float):
	var tier=24 if size<=32 else (48 if size<=64 else 96)
	c.texture_filter=CanvasItem.TEXTURE_FILTER_NEAREST
	c.draw_texture_rect(RESOURCES[kind][tier],Rect2((center-Vector2.ONE*size*0.5).round(),Vector2.ONE*size),false)

static func carry(c: CanvasItem, action: String, facing: int, foot: Vector2, elapsed: float):
	var key="enemy/"+action+("_left" if facing<0 else "_right")
	var frame=CLIPS[key].frames[frame_index(key,elapsed)]
	var corner=(foot-Vector2(16,44)).round()
	c.texture_filter=CanvasItem.TEXTURE_FILTER_NEAREST
	c.draw_texture(frame.rear,corner)
	# Rotate the unchanged keeper -90 degrees; mirror the rotated result for left.
	var x=Vector2(0,-1)
	var y=Vector2(-1 if facing<0 else 1,0)
	var support=corner+frame.shoulder
	c.draw_set_transform_matrix(Transform2D(x,y,support-x*6-y*26))
	c.draw_texture(preload("res://art_delivery/characters_v1/keeper_idle_right_00.png"),Vector2.ZERO)
	c.draw_set_transform(Vector2.ZERO)
	c.draw_texture(frame.front,corner)
''']
(ROOT/'game/delivered_art.gd').write_text('\n'.join(rows),encoding='utf-8')
