"""Rebuild preload catalogue and verify the adopted delivery; never modify PNGs."""
import hashlib, json, pathlib, subprocess
import re
root = pathlib.Path(__file__).resolve().parents[1]
actors = ('merchant', 'maid', 'dancer', 'thief', 'cow', 'bull')
sha = subprocess.check_output(['git', 'rev-parse', 'origin/codex/sporehollow-art-assets'], text=True).strip()
rows, receipt = [], {'delivery_commit': sha, 'files': {}}
for actor in actors:
    folder = root / 'art_delivery' / (actor + '_motion_v1')
    manifest = json.loads((folder / 'manifest.json').read_text(encoding='utf-8-sig'))
    groups = {}
    for frame in manifest['assets']:
        path = folder / frame['file']
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        assert digest == frame['sha256'], path
        rel = path.relative_to(root).as_posix()
        receipt['files'][rel] = digest
        groups.setdefault((frame['action'], frame['direction']), []).append(frame)
    for (action, direction), frames in groups.items():
        frames.sort(key=lambda f: f['frame_index'])
        encoded=[]
        for f in frames:
            anchor=f['foot_anchor_px']; path=f'art_delivery/{actor}_motion_v1/{f["file"]}'
            encoded.append('{"texture":preload("res://'+path+'"),"anchor":Vector2(%s,%s),"ms":%s,"sockets":%s}' % (*anchor, f['frame_duration_ms'] or 1000, json.dumps(f.get('sockets_px',{}))))
        rows.append('"%s/%s/%s":{"loop":%s,"frames":[%s]}' % (actor,action,direction,str(frames[0]['loop']).lower(),','.join(encoded)))
    (folder/'preview'/'.gdignore').write_text('',encoding='utf-8')
(root/'game/six_motion_clips.gd').write_text('extends RefCounted\n# Generated by tools/import_six_motion.py from verified manifests.\nconst CLIPS={\n'+',\n'.join(rows)+'\n}\n',encoding='utf-8')
(root/'game/six_motion_receipt.json').write_text(json.dumps(receipt,indent=2)+'\n',encoding='utf-8')
p=root/'game/art_provenance.json'; data=json.loads(p.read_text(encoding='utf-8-sig'))
data['latest_delivery_commit']=sha
for actor in actors:data[actor+'_motion_v1']=sha
data['six_motion']='game/six_motion_receipt.json'
p.write_text(json.dumps(data,indent=2)+'\n',encoding='utf-8')
p=root/'game/direction_art.gd'; text=p.read_text(encoding='utf-8-sig')
for actor in actors[1:]:
    key='new.'+actor if actor in ('cow','bull') else actor+'.idle'
    m=json.loads((root/'art_delivery'/f'{actor}_motion_v1'/'manifest.json').read_text(encoding='utf-8-sig'))
    f=next(f for f in m['assets'] if f['file']=='idle/right_00.png')
    row='"'+key+'":{"texture":preload("res://art_delivery/'+actor+'_motion_v1/idle/right_00.png"),"anchor":Vector2(%s, %s)}' % tuple(f['foot_anchor_px'])
    text=re.sub(r'"'+re.escape(key)+r'":\{[^\n]+?\}',lambda _:row,text,count=1)
p.write_text(text,encoding='utf-8')
print('Verified PNGs:',len(receipt['files']), 'clips:',len(rows), 'source:',sha)
