extends SceneTree
const Farm=preload("res://game/world.gd")
const Art=preload("res://game/delivered_art.gd")
var game
var output=""
var checks=0
var failures=0
var shots=[]
func _initialize():call_deferred("run")
func check(ok: bool, message: String):
	checks+=1
	if not ok:failures+=1;push_error(message)
func frame(delta=0.033333):
	game._process(delta)
	await process_frame
func capture(name: String):
	if output=="":return
	await process_frame;await RenderingServer.frame_post_draw
	root.get_texture().get_image().save_png(output+"/"+name+".png")
	shots.append({"file":name+".png","enemies":game.enemy_art.duplicate(true),"effects":game.dust.duplicate(true),"tick":game.world.tick})
func run():
	output=OS.get_environment("FARM_REVIEW_OUTPUT")
	if DisplayServer.get_name()!="headless" and (output=="" or not "--isolated-review" in OS.get_cmdline_user_args()):quit(2);return
	root.size=Vector2i(1280,800)
	game=load("res://game/main.tscn").instantiate();game.automated=true
	game.world=Farm.new({},17).begin_day();root.add_child(game);game.set_process(false)
	await process_frame
	var w=game.world
	w.animals[0].pos=Vector2i(8,9);w.animals[0].mode="stay"
	w.keeper.pos=Vector2i(11,8)
	w.spawn_enemy({"entry":Vector2i(10,8),"role":"kidnapper"})
	var e=w.enemies[0]
	game.reset_view();game.automated=true;game.group=-1;game.camera.zoom=Vector2(2,2);game.camera.position=game.center(Vector2i(11,8))
	await frame();await capture("enemy_search")
	for facing in [-1,1]:
		var suffix="left" if facing<0 else "right"
		game.enemy_art[e.id].facing=facing
		for action in ["idle","walk","attack","search","discovery","hit","retreat","carry_idle","carry_walk"]:
			# Presentation fixtures only: use the same draw_enemy_actor as gameplay.
			e.carry="keeper" if action.begins_with("carry") else ""
			w.keeper.carrier=e.id if e.carry!="" else -1
			game.enemy_art[e.id]={"action":action,"facing":facing,"at":game.visual_time,"walking":action=="carry_walk"}
			var key="enemy/"+action+"_"+suffix
			var elapsed=0.0
			for i in range(Art.CLIPS[key].times.size()):
				game.enemy_art[e.id].at=game.visual_time-elapsed-0.01
				game.queue_redraw();await capture(action+"_"+suffix+"_%02d"%i)
				elapsed+=Art.CLIPS[key].times[i]
			check(Art.frame_index(key,elapsed+1)>=0,"Enemy final/loop frame exists "+key)
	e.carry="";w.keeper.carrier=-1
	game.enemy_art.clear();await frame()
	# Existing combat records trigger visual responses once; no damage is generated by art.
	var hp=e.hp
	w.combat_log.append({"tick":w.tick,"source":"keeper","id":0,"target":e.id,"damage":2})
	await frame();check(game.enemy_art[e.id].action=="hit" and e.hp==hp,"Existing hit event selects art without changing HP")
	await capture("event_hit")
	w.paused=true
	var time=game.visual_time
	await frame(1.0);check(game.visual_time==time,"Pause freezes enemy and effect clock")
	w.paused=false
	for i in range(15):await frame()
	check(game.dust.is_empty() and game.enemy_art[e.id].action!="hit","One-shot reaction and effect expire")
	# All delivered effect frames disappear, never hold the last fragment.
	for key in Art.CLIPS:
		if not key.begins_with("fx/"):continue
		check(Art.frame_index(key,Art.duration(key)+0.01,true)==-1,"Effect expires "+key)
	for i in range(4):
		game.dust.clear()
		var index=0
		for key in Art.CLIPS:
			if not key.begins_with("fx/"):continue
			var elapsed=0.01
			for n in range(i):elapsed+=Art.CLIPS[key].times[n]
			game.dust.append({"kind":key.trim_prefix("fx/"),"at":game.visual_time-elapsed,"pos":game.center(Vector2i(8+index%5,7+index/5))})
			index+=1
		game.queue_redraw();await capture("effects_%02d"%i)
	game.dust.clear()
	# Exercise an actual construction job and collect job through normal simulation.
	w.enemies.clear();w.keeper.pos=Vector2i(7,13);game.view_positions.clear();game.actor_tracks.clear()
	w.act("wall",Vector2i(8,13))
	for i in range(12):w.step();await frame()
	check(w.structures.get(Vector2i(8,13),{}).get("status")=="ready","Actual build still completes")
	w.natural[Vector2i(7,12)]="stump";w.act("collect",Vector2i(7,12))
	var saw_collect=false
	for i in range(40):
		w.step();await frame()
		if game.dust.any(func(f):return f.kind=="item_collect"):saw_collect=true
	check(saw_collect,"Actual collect event emits delivered pickup")
	game.reset_view();check(game.enemy_art.is_empty() and game.dust.is_empty(),"Retry removes transient art")
	# Normal damage -> unconscious -> carried -> dog rescue, from controlled initial positions.
	var config=Farm.StageData.STAGES[1].duplicate(true)
	config.first_attack_seconds=9999.0
	w=Farm.new({},17,config).begin_day();game.world=w
	w.keeper.pos=Vector2i(19,8);w.animals[0].pos=Vector2i(19,10);w.animals[0].mode="rest"
	w.start_night();w.spawn_enemy({"entry":Vector2i(1,5),"role":"kidnapper","lv":1});w.enemies[0].pos=Vector2i(18,8)
	game.reset_view();game.automated=true;game.camera.zoom=Vector2(2,2);game.camera.position=game.center(Vector2i(18,8))
	var down=false;var carried=false;var combat=false
	for i in range(650):
		w.step();await frame(0.25)
		if not combat and w.combat_log.size()>0:combat=true;await capture("live_combat")
		if not down and w.keeper.state=="unconscious":down=true;await capture("live_unconscious")
		if not carried and w.keeper.carrier>=0:
			carried=true;await capture("live_carried")
			check(game.keeper_hit_rect().has_point(game.keeper_pixel()),"Carried keeper selection follows visible shoulder composition")
			w.animals[0].mode="auto" # Release fixture's explicit rest, as in existing keeper regression.
		if w.metrics.rescues>0:await capture("live_rescued");break
	check(combat and down and carried and w.metrics.rescues==1,"Normal combat, down, carry and dog rescue with new drawing")
	if output!="":FileAccess.open(output+"/observations.json",FileAccess.WRITE).store_string(JSON.stringify({"implementation_commit":OS.get_environment("FARM_REVIEW_COMMIT"),"method":"Actual game draw functions; scripted presentation fixtures for all delivered frames, normal construction/collection simulation; not a full night playthrough","checks":checks,"failures":failures,"shots":shots},"  "))
	print("DELIVERED_ART: ",checks," checks failures=",failures)
	quit(0 if failures==0 else 1)
