extends RefCounted
# Generated by tools/compile_delivered_art.py from unmodified delivery manifests.
const CLIPS = {
	"enemy/idle_right":{"frames":[preload("res://art_delivery/kidnapper_basic_v1/idle/right_00.png")],"times":[1.0],"loop":false,"anchor":Vector2(16, 44)},
	"enemy/idle_left":{"frames":[preload("res://art_delivery/kidnapper_basic_v1/idle/left_00.png")],"times":[1.0],"loop":false,"anchor":Vector2(16, 44)},
	"enemy/walk_right":{"frames":[preload("res://art_delivery/kidnapper_basic_v1/walk/right_00.png"),preload("res://art_delivery/kidnapper_basic_v1/walk/right_01.png"),preload("res://art_delivery/kidnapper_basic_v1/walk/right_02.png"),preload("res://art_delivery/kidnapper_basic_v1/walk/right_03.png")],"times":[0.12, 0.12, 0.12, 0.12],"loop":true,"anchor":Vector2(16, 44)},
	"enemy/walk_left":{"frames":[preload("res://art_delivery/kidnapper_basic_v1/walk/left_00.png"),preload("res://art_delivery/kidnapper_basic_v1/walk/left_01.png"),preload("res://art_delivery/kidnapper_basic_v1/walk/left_02.png"),preload("res://art_delivery/kidnapper_basic_v1/walk/left_03.png")],"times":[0.12, 0.12, 0.12, 0.12],"loop":true,"anchor":Vector2(16, 44)},
	"enemy/attack_right":{"frames":[preload("res://art_delivery/kidnapper_basic_v1/attack/right_00.png"),preload("res://art_delivery/kidnapper_basic_v1/attack/right_01.png"),preload("res://art_delivery/kidnapper_basic_v1/attack/right_02.png")],"times":[0.13, 0.08, 0.14],"loop":false,"anchor":Vector2(16, 44)},
	"enemy/attack_left":{"frames":[preload("res://art_delivery/kidnapper_basic_v1/attack/left_00.png"),preload("res://art_delivery/kidnapper_basic_v1/attack/left_01.png"),preload("res://art_delivery/kidnapper_basic_v1/attack/left_02.png")],"times":[0.13, 0.08, 0.14],"loop":false,"anchor":Vector2(16, 44)},
	"enemy/carry_idle_right":{"frames":[{"rear":preload("res://art_delivery/kidnapper_basic_v1/carry/right_00_rear.png"),"front":preload("res://art_delivery/kidnapper_basic_v1/carry/right_00_front.png"),"shoulder":Vector2(12, 16)}],"times":[1.0],"loop":false,"anchor":Vector2(16, 44)},
	"enemy/carry_walk_right":{"frames":[{"rear":preload("res://art_delivery/kidnapper_basic_v1/carry/right_01_rear.png"),"front":preload("res://art_delivery/kidnapper_basic_v1/carry/right_01_front.png"),"shoulder":Vector2(12, 16)},{"rear":preload("res://art_delivery/kidnapper_basic_v1/carry/right_02_rear.png"),"front":preload("res://art_delivery/kidnapper_basic_v1/carry/right_02_front.png"),"shoulder":Vector2(12, 16)}],"times":[0.15, 0.15],"loop":true,"anchor":Vector2(16, 44)},
	"enemy/carry_idle_left":{"frames":[{"rear":preload("res://art_delivery/kidnapper_basic_v1/carry/left_00_rear.png"),"front":preload("res://art_delivery/kidnapper_basic_v1/carry/left_00_front.png"),"shoulder":Vector2(20, 16)}],"times":[1.0],"loop":false,"anchor":Vector2(16, 44)},
	"enemy/carry_walk_left":{"frames":[{"rear":preload("res://art_delivery/kidnapper_basic_v1/carry/left_01_rear.png"),"front":preload("res://art_delivery/kidnapper_basic_v1/carry/left_01_front.png"),"shoulder":Vector2(20, 16)},{"rear":preload("res://art_delivery/kidnapper_basic_v1/carry/left_02_rear.png"),"front":preload("res://art_delivery/kidnapper_basic_v1/carry/left_02_front.png"),"shoulder":Vector2(20, 16)}],"times":[0.15, 0.15],"loop":true,"anchor":Vector2(16, 44)},
	"enemy/structure_attack_right":{"frames":[preload("res://art_delivery/kidnapper_basic_v1/attack/right_00.png"),preload("res://art_delivery/kidnapper_basic_v1/attack/right_01.png"),preload("res://art_delivery/kidnapper_basic_v1/attack/right_02.png")],"times":[0.13, 0.08, 0.14],"loop":false,"anchor":Vector2(16, 44)},
	"enemy/structure_attack_left":{"frames":[preload("res://art_delivery/kidnapper_basic_v1/attack/left_00.png"),preload("res://art_delivery/kidnapper_basic_v1/attack/left_01.png"),preload("res://art_delivery/kidnapper_basic_v1/attack/left_02.png")],"times":[0.13, 0.08, 0.14],"loop":false,"anchor":Vector2(16, 44)},
	"enemy/search_right":{"frames":[preload("res://art_delivery/kidnapper_reactions_v1/search/right_00.png"),preload("res://art_delivery/kidnapper_reactions_v1/search/right_01.png"),preload("res://art_delivery/kidnapper_reactions_v1/search/right_02.png")],"times":[0.3, 0.45, 0.25],"loop":false,"anchor":Vector2(16, 44)},
	"enemy/search_left":{"frames":[preload("res://art_delivery/kidnapper_reactions_v1/search/left_00.png"),preload("res://art_delivery/kidnapper_reactions_v1/search/left_01.png"),preload("res://art_delivery/kidnapper_reactions_v1/search/left_02.png")],"times":[0.3, 0.45, 0.25],"loop":false,"anchor":Vector2(16, 44)},
	"enemy/discovery_right":{"frames":[preload("res://art_delivery/kidnapper_reactions_v1/discovery/right_00.png"),preload("res://art_delivery/kidnapper_reactions_v1/discovery/right_01.png")],"times":[0.12, 0.18],"loop":false,"anchor":Vector2(16, 44)},
	"enemy/discovery_left":{"frames":[preload("res://art_delivery/kidnapper_reactions_v1/discovery/left_00.png"),preload("res://art_delivery/kidnapper_reactions_v1/discovery/left_01.png")],"times":[0.12, 0.18],"loop":false,"anchor":Vector2(16, 44)},
	"enemy/hit_right":{"frames":[preload("res://art_delivery/kidnapper_reactions_v1/hit/right_00.png"),preload("res://art_delivery/kidnapper_reactions_v1/hit/right_01.png")],"times":[0.1, 0.14],"loop":false,"anchor":Vector2(16, 44)},
	"enemy/hit_left":{"frames":[preload("res://art_delivery/kidnapper_reactions_v1/hit/left_00.png"),preload("res://art_delivery/kidnapper_reactions_v1/hit/left_01.png")],"times":[0.1, 0.14],"loop":false,"anchor":Vector2(16, 44)},
	"enemy/retreat_right":{"frames":[preload("res://art_delivery/kidnapper_reactions_v1/retreat/right_00.png"),preload("res://art_delivery/kidnapper_reactions_v1/retreat/right_01.png"),preload("res://art_delivery/kidnapper_reactions_v1/retreat/right_02.png"),preload("res://art_delivery/kidnapper_reactions_v1/retreat/right_03.png")],"times":[0.09, 0.09, 0.09, 0.09],"loop":true,"anchor":Vector2(16, 44)},
	"enemy/retreat_left":{"frames":[preload("res://art_delivery/kidnapper_reactions_v1/retreat/left_00.png"),preload("res://art_delivery/kidnapper_reactions_v1/retreat/left_01.png"),preload("res://art_delivery/kidnapper_reactions_v1/retreat/left_02.png"),preload("res://art_delivery/kidnapper_reactions_v1/retreat/left_03.png")],"times":[0.09, 0.09, 0.09, 0.09],"loop":true,"anchor":Vector2(16, 44)},
	"fx/soil_dust":{"frames":[preload("res://art_delivery/effects_v1/soil_dust/00.png"),preload("res://art_delivery/effects_v1/soil_dust/01.png"),preload("res://art_delivery/effects_v1/soil_dust/02.png"),preload("res://art_delivery/effects_v1/soil_dust/03.png")],"times":[0.07, 0.08, 0.09, 0.1],"loop":false,"anchor":Vector2(16, 26)},
	"fx/wood_chips":{"frames":[preload("res://art_delivery/effects_v1/wood_chips/00.png"),preload("res://art_delivery/effects_v1/wood_chips/01.png"),preload("res://art_delivery/effects_v1/wood_chips/02.png"),preload("res://art_delivery/effects_v1/wood_chips/03.png")],"times":[0.06, 0.07, 0.09, 0.1],"loop":false,"anchor":Vector2(16, 26)},
	"fx/stone_powder":{"frames":[preload("res://art_delivery/effects_v1/stone_powder/00.png"),preload("res://art_delivery/effects_v1/stone_powder/01.png"),preload("res://art_delivery/effects_v1/stone_powder/02.png"),preload("res://art_delivery/effects_v1/stone_powder/03.png")],"times":[0.07, 0.08, 0.09, 0.1],"loop":false,"anchor":Vector2(16, 26)},
	"fx/build_complete":{"frames":[preload("res://art_delivery/effects_v1/build_complete/00.png"),preload("res://art_delivery/effects_v1/build_complete/01.png"),preload("res://art_delivery/effects_v1/build_complete/02.png"),preload("res://art_delivery/effects_v1/build_complete/03.png")],"times":[0.08, 0.11, 0.1, 0.11],"loop":false,"anchor":Vector2(16, 16)},
	"fx/attack_hit":{"frames":[preload("res://art_delivery/effects_v1/attack_hit/00.png"),preload("res://art_delivery/effects_v1/attack_hit/01.png"),preload("res://art_delivery/effects_v1/attack_hit/02.png"),preload("res://art_delivery/effects_v1/attack_hit/03.png")],"times":[0.05, 0.06, 0.07, 0.08],"loop":false,"anchor":Vector2(16, 16)},
	"fx/hurt":{"frames":[preload("res://art_delivery/effects_v1/hurt/00.png"),preload("res://art_delivery/effects_v1/hurt/01.png"),preload("res://art_delivery/effects_v1/hurt/02.png"),preload("res://art_delivery/effects_v1/hurt/03.png")],"times":[0.06, 0.07, 0.08, 0.09],"loop":false,"anchor":Vector2(16, 16)},
	"fx/item_collect":{"frames":[preload("res://art_delivery/effects_v1/item_collect/00.png"),preload("res://art_delivery/effects_v1/item_collect/01.png"),preload("res://art_delivery/effects_v1/item_collect/02.png"),preload("res://art_delivery/effects_v1/item_collect/03.png")],"times":[0.07, 0.09, 0.09, 0.09],"loop":false,"anchor":Vector2(16, 16)},
	"fx/sound_wave":{"frames":[preload("res://art_delivery/effects_v1/sound_wave/00.png"),preload("res://art_delivery/effects_v1/sound_wave/01.png"),preload("res://art_delivery/effects_v1/sound_wave/02.png"),preload("res://art_delivery/effects_v1/sound_wave/03.png")],"times":[0.07, 0.09, 0.1, 0.1],"loop":false,"anchor":Vector2(4, 16)},
	"fx/sound_wave_left":{"frames":[preload("res://art_delivery/effects_v1/sound_wave_left/00.png"),preload("res://art_delivery/effects_v1/sound_wave_left/01.png"),preload("res://art_delivery/effects_v1/sound_wave_left/02.png"),preload("res://art_delivery/effects_v1/sound_wave_left/03.png")],"times":[0.07, 0.09, 0.1, 0.1],"loop":false,"anchor":Vector2(28, 16)},
	"fx/lock_break":{"frames":[preload("res://art_delivery/effects_v1/lock_break/00.png"),preload("res://art_delivery/effects_v1/lock_break/01.png"),preload("res://art_delivery/effects_v1/lock_break/02.png"),preload("res://art_delivery/effects_v1/lock_break/03.png")],"times":[0.07, 0.08, 0.09, 0.11],"loop":false,"anchor":Vector2(16, 16)},
}
const RESOURCES = {
	"wood":{24:preload("res://art_delivery/resource_icons_v1/hud24/wood.png"),48:preload("res://art_delivery/resource_icons_v1/ui48/wood.png"),96:preload("res://art_delivery/resource_icons_v1/ui96/wood.png")},
	"soil":{24:preload("res://art_delivery/resource_icons_v1/hud24/soil.png"),48:preload("res://art_delivery/resource_icons_v1/ui48/soil.png"),96:preload("res://art_delivery/resource_icons_v1/ui96/soil.png")},
	"stone":{24:preload("res://art_delivery/resource_icons_v1/hud24/stone.png"),48:preload("res://art_delivery/resource_icons_v1/ui48/stone.png"),96:preload("res://art_delivery/resource_icons_v1/ui96/stone.png")},
	"gold":{24:preload("res://art_delivery/resource_icons_v1/hud24/gold.png"),48:preload("res://art_delivery/resource_icons_v1/ui48/gold.png"),96:preload("res://art_delivery/resource_icons_v1/ui96/gold.png")},
}

static func duration(key: String) -> float:
	var total=0.0
	for seconds in CLIPS[key].times: total+=seconds
	return total

static func frame_index(key: String, elapsed: float, hide_finished: bool=false) -> int:
	var clip=CLIPS[key]
	var total=duration(key)
	if hide_finished and elapsed>=total and not clip.loop:return -1
	var time=fmod(maxf(elapsed,0),total) if clip.loop else maxf(elapsed,0)
	for i in range(clip.times.size()):
		if time<clip.times[i]:return i
		time-=clip.times[i]
	return clip.frames.size()-1

static func draw_clip(c: CanvasItem, key: String, origin: Vector2, elapsed: float):
	var index=frame_index(key,elapsed,key.begins_with("fx/"))
	if index<0:return
	c.texture_filter=CanvasItem.TEXTURE_FILTER_NEAREST
	c.draw_texture(CLIPS[key].frames[index],(origin-CLIPS[key].anchor).round())

static func resource(c: CanvasItem, kind: String, center: Vector2, size: float):
	var tier=24 if size<=32 else (48 if size<=64 else 96)
	c.texture_filter=CanvasItem.TEXTURE_FILTER_NEAREST
	c.draw_texture_rect(RESOURCES[kind][tier],Rect2((center-Vector2.ONE*size*0.5).round(),Vector2.ONE*size),false)

static func carry(c: CanvasItem, action: String, facing: int, foot: Vector2, elapsed: float):
	var key="enemy/"+action+("_left" if facing<0 else "_right")
	var frame=CLIPS[key].frames[frame_index(key,elapsed)]
	var corner=(foot-Vector2(16,44)).round()
	c.texture_filter=CanvasItem.TEXTURE_FILTER_NEAREST
	c.draw_texture(frame.rear,corner)
	# Rotate the unchanged keeper -90 degrees; mirror the rotated result for left.
	var x=Vector2(0,-1)
	var y=Vector2(-1 if facing<0 else 1,0)
	var support=corner+frame.shoulder
	c.draw_set_transform_matrix(Transform2D(x,y,support-x*6-y*26))
	c.draw_texture(preload("res://art_delivery/characters_v1/keeper_idle_right_00.png"),Vector2.ZERO)
	c.draw_set_transform(Vector2.ZERO)
	c.draw_texture(frame.front,corner)
